version: "3.9"

services:
  core:
    container_name: iram-backend-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 3002:3001
    env_file:
      - .env
    command: npm start
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/postgres/postgres.conf:/postgres/config/postgres.conf
      - ./configs/postgres/passwd:/etc/postgres/passwd
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres


volumes:
  postgres_data: